version: '3'

services:
  db:
    image: postgres
    ports:
      - '5432:5432'
    container_name: postgres
    environment:
      - POSTGRES_DB=springsample
      - POSTGRES_USER=sampleuser
      - POSTGRES_PASSWORD=samplesecret
    restart: always

  redis:
    image: redis
    ports:
      - '6379:6379'
    container_name: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - RESDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    restart: always

  app:
    image: vamos-server
    container_name: vamos-server
    ports:
      - '8080:8080'
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db/postgres
      SPRING_DATASOURCE_USERNAME: sampleuser
      SPRING_DATASOURCE_PASSWORD: samplesecret
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_POST: 6379
    depends_on:
      - db
      - redis
    restart: always