spring:

  application:
    name: vamos

  profiles:
    active: pg
    include: oauth,property

#  session:
#    store-type: jdbc

  web:
    resources:
      add-mappings: false

  mvc:
    throw-exception-if-no-handler-found: true