spring:
  application:
    name: vamos
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database: h2
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.dialect: org.hibernate.dialect.H2Dialect
  datasource:
    platform: h2
    driver-class-name: org.h2.Driver
    url: "jdbc:h2:mem:vamos;MODE=PostgreSQL"
    data-username: sa
    data-password:
server:
  port: 8080