spring:

  application:
    name: vamos

  web:
    resources:
      add-mappings: false

  mvc:
    throw-exception-if-no-handler-found: true

  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        format_sql: true
        use_sql_comments: true

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/vamos
    data-username: jun
    data-password: 2457
    initialization-mode: always
    platform: postgres

  redis:
    host: 127.0.0.1
    password:
    port: 6379

server:
  port: 8080
