spring:
  application:
    name: vamos
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        format_sql: true
  datasource:
#    platform: h2
    driver-class-name: org.h2.Driver
    url: "jdbc:h2:mem:vamos;MODE=PostgreSQL"
    data-username: sa
    data-password:
  redis:
    host: 127.0.0.1
    password:
    port: 6379
server:
  port: 8080

jwt:
  header: Authorization
  #echo 'shinjunseok-project-spring-boot-jwt-authorization-secret-shinjunseok-project-spring-boot-jwt-authorization-secret'|base64
  secret: c2hpbmp1bnNlb2stcHJvamVjdC1zcHJpbmctYm9vdC1qd3QtYXV0aG9yaXphdGlvbi1zZWNyZXQtc2hpbmp1bnNlb2stcHJvamVjdC1zcHJpbmctYm9vdC1qd3QtYXV0aG9yaXphdGlvbi1zZWNyZXQK
  token-validity-in-seconds: 86400