spring:
  application:
    name: vamos
  web:
    resources:
      add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        format_sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/vamos
    data-username: jun
    data-password: 2457
    initialization-mode: always
    platform: postgres
  redis:
    host: 127.0.0.1
    password:
    port: 6379
server:
  port: 8080

jwt:
  header: ${jwt_header:header}
  secret: ${jwt_secret:secret}
  token-validity-in-seconds: ${jwt_token_validity_in_seconds:validity}

ncs:
  accessKey: ${ncs_access_key:key}
  secretKey: ${ncs_secret:secret}
  serviceId: ${ncs_service_id:id}
  from: ${ncs_from:from}

