INSERT INTO AUTHORITY (AUTHORITY_NAME) values ('ROLE_USER');
INSERT INTO AUTHORITY (AUTHORITY_NAME) values ('ROLE_ADMIN');

INSERT INTO USERS (ID, USERNAME, PASSWORD, NICKNAME, PHONE_NUMBER) values (0, 'admin', '$2a$10$wc/Je/WEvp2.0A3FcAe1jeN8UkZYQ.Irxqks4XSL63pUz/Dg1zI4a', 'admin', '01053402457');
INSERT INTO USER_AUTHORITY (USER_ID, AUTHORITY_NAME) values (0, 'ROLE_ADMIN');
INSERT INTO USER_AUTHORITY (USER_ID, AUTHORITY_NAME) values (0, 'ROLE_USER');