INSERT INTO CATEGORY (ID, NAME)
VALUES (1, 'DIGITAL_DEVICE')
ON CONFLICT DO NOTHING;
INSERT INTO CATEGORY (ID, NAME)
VALUES (2, 'HOME_APPLIANCES')
ON CONFLICT DO NOTHING;
INSERT INTO CATEGORY (ID, NAME)
VALUES (3, 'FURNITURE_INTERIOR')
ON CONFLICT DO NOTHING;
INSERT INTO CATEGORY (ID, NAME)
VALUES (4, 'INFANT_CHILD')
ON CONFLICT DO NOTHING;
INSERT INTO CATEGORY (ID, NAME)
VALUES (5, 'TODDLER_BOOK')
ON CONFLICT DO NOTHING;
INSERT INTO CATEGORY (ID, NAME)
VALUES (6, 'PROCESSED_FOOD')
ON CONFLICT DO NOTHING;
INSERT INTO CATEGORY (ID, NAME)
VALUES (7, 'SPORTS_LEISURE')
ON CONFLICT DO NOTHING;
INSERT INTO CATEGORY (ID, NAME)
VALUES (8, 'WOMEN_FASHION')
ON CONFLICT DO NOTHING;
INSERT INTO CATEGORY (ID, NAME)
VALUES (9, 'MEN_FASHION')
ON CONFLICT DO NOTHING;
INSERT INTO CATEGORY (ID, NAME)
VALUES (10, 'GAME_HOBBY')
ON CONFLICT DO NOTHING;
INSERT INTO CATEGORY (ID, NAME)
VALUES (11, 'BEAUTY')
ON CONFLICT DO NOTHING;
INSERT INTO CATEGORY (ID, NAME)
VALUES (12, 'PET_SUPPLIES')
ON CONFLICT DO NOTHING;
INSERT INTO CATEGORY (ID, NAME)
VALUES (13, 'BOOKS_TICKETS_RECORDS')
ON CONFLICT DO NOTHING;
INSERT INTO CATEGORY (ID, NAME)
VALUES (14, 'PLANT')
ON CONFLICT DO NOTHING;
INSERT INTO CATEGORY (ID, NAME)
VALUES (15, 'ETC')
ON CONFLICT DO NOTHING;
INSERT INTO CATEGORY (ID, NAME)
VALUES (16, 'WANT_BUY')
ON CONFLICT DO NOTHING;


